# Generated by Django 3.2 on 2021-04-12 20:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id_book', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=194, verbose_name='Título:')),
                ('author', models.CharField(max_length=194, verbose_name='Autor:')),
                ('release_year', models.IntegerField(verbose_name='Ano lançamento:')),
                ('state', models.CharField(max_length=10, verbose_name='Estado do livro:')),
                ('pages', models.IntegerField(verbose_name='Número de paginas:')),
                ('publishing', models.CharField(max_length=194, verbose_name='Editora:')),
                ('creat_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
