# Generated by Django 3.2 on 2021-04-13 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_books_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Nome:')),
                ('birthday', models.DateField(verbose_name='Data de nascimento:')),
                ('genero', models.CharField(max_length=20, verbose_name='Genero da escrita:')),
                ('city', models.CharField(max_length=90, verbose_name='Cidade de nascimnto:')),
                ('about', models.TextField(max_length=500, verbose_name='Sobre o autor:')),
            ],
        ),
        migrations.AlterField(
            model_name='books',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.author'),
        ),
    ]
