# Generated by Django 3.2 on 2021-04-13 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_author_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='about',
            field=models.TextField(max_length=100, verbose_name='Sobre o autor:'),
        ),
    ]
